apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cp-demo-1778503916
  description: "AWS CodePipeline end-to-end demo: GHA to ECR to Pipeline to ArgoCD"
  annotations:
    github.com/project-slug: priyankaajbhagatt-collab/cp-demo-1778503916
    backstage.io/techdocs-ref: dir:.
    argocd/app-selector: service=cp-demo-1778503916
    backstage.io/kubernetes-label-selector: app=cp-demo-1778503916
    aws.amazon.com/aws-codepipeline-tags: Service=cp-demo-1778503916
  tags:
    - java
    - spring-boot
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: devex-scaffolder
  dependsOn:
    - resource:default/cp-demo-1778503916-pipeline
    - resource:default/cp-demo-1778503916-ecr
